CREATE TABLE [dbo].[Countries]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] VARCHAR(32) NOT NULL UNIQUE,
	[ParentID] INT NOT NULL,
	[Latitude] FLOAT NOT NULL DEFAULT 0.0,
	[Longitude] FLOAT NOT NULL DEFAULT 0.0
)
